"""create_bookings_and_gist

Revision ID: 2131e74c72f9
Revises: c2f6f70806e9
Create Date: 2026-08-08 22:43:43.525911

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2131e74c72f9"
down_revision: Union[str, Sequence[str], None] = "c2f6f70806e9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bookings",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("business_id", sa.UUID(), nullable=False),
        sa.Column("service_id", sa.UUID(), nullable=False),
        sa.Column("provider_id", sa.UUID(), nullable=False),
        sa.Column("public_reference", sa.String(length=64), nullable=False),
        sa.Column("client_request_id", sa.UUID(), nullable=True),
        sa.Column("customer_name", sa.String(length=120), nullable=False),
        sa.Column("customer_email", sa.String(length=254), nullable=False),
        sa.Column("customer_phone", sa.String(length=32), nullable=False),
        sa.Column("customer_notes", sa.Text(), nullable=False),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM("confirmed", "completed", "cancelled", "no_show", name="booking_status", create_type=False),
            nullable=False,
        ),  # noqa: E501
        sa.Column(
            "source", postgresql.ENUM("public", "admin", name="booking_source", create_type=False), nullable=False
        ),  # noqa: E501
        sa.Column("service_name_snapshot", sa.String(length=120), nullable=False),
        sa.Column("duration_minutes_snapshot", sa.Integer(), nullable=False),
        sa.Column("price_amount_snapshot", sa.Integer(), nullable=False),
        sa.Column("provider_name_snapshot", sa.String(length=120), nullable=False),
        sa.Column(
            "email_delivery_status",
            postgresql.ENUM(
                "not_requested", "pending", "sent", "failed", name="email_delivery_status", create_type=False
            ),
            nullable=False,
        ),  # noqa: E501
        sa.Column("email_provider_id", sa.String(length=160), nullable=True),
        sa.Column("email_sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("email_last_error_code", sa.String(length=80), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        postgresql.ExcludeConstraint(
            (sa.column("provider_id"), "="),
            (sa.text("tstzrange(starts_at, ends_at, '[)')"), "&&"),
            where=sa.text("status != 'cancelled'"),
            using="gist",
            name="bookings_provider_no_overlap",
        ),
        sa.CheckConstraint("duration_minutes_snapshot > 0", name="check_booking_duration"),
        sa.CheckConstraint("ends_at > starts_at", name="check_booking_ends_at"),
        sa.CheckConstraint("price_amount_snapshot >= 0", name="check_booking_price"),
        sa.ForeignKeyConstraint(
            ["business_id", "provider_id"], ["providers.business_id", "providers.id"], ondelete="RESTRICT"
        ),  # noqa: E501
        sa.ForeignKeyConstraint(
            ["business_id", "service_id"], ["services.business_id", "services.id"], ondelete="RESTRICT"
        ),  # noqa: E501
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("business_id", "client_request_id", name="uq_business_client_request"),
        sa.UniqueConstraint("public_reference"),
    )
    op.create_index(
        "ix_bookings_business_provider_starts", "bookings", ["business_id", "provider_id", "starts_at"], unique=False
    )  # noqa: E501
    op.create_index("ix_bookings_business_starts", "bookings", ["business_id", "starts_at"], unique=False)
    op.create_index(
        "ix_bookings_business_status_starts", "bookings", ["business_id", "status", "starts_at"], unique=False
    )  # noqa: E501
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_bookings_business_status_starts", table_name="bookings")
    op.drop_index("ix_bookings_business_starts", table_name="bookings")
    op.drop_index("ix_bookings_business_provider_starts", table_name="bookings")
    op.drop_table("bookings")
    # ### end Alembic commands ###
