"""add_request_fingerprint_to_bookings

Revision ID: 6e25a42aaedd
Revises: 2131e74c72f9
Create Date: 2026-08-09 14:54:20.209638

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6e25a42aaedd"
down_revision: Union[str, Sequence[str], None] = "2131e74c72f9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("bookings", sa.Column("request_fingerprint", sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("bookings", "request_fingerprint")
    # ### end Alembic commands ###
