"""create_catalog_tables

Revision ID: b24f49968702
Revises: caa00e08ebad
Create Date: 2026-08-08 22:43:25.289939

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b24f49968702"
down_revision: Union[str, Sequence[str], None] = "caa00e08ebad"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "providers",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("business_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("email", sa.String(length=254), nullable=True),
        sa.Column("phone", sa.String(length=32), nullable=True),
        sa.Column("bio", sa.Text(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["business_id"], ["businesses.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("business_id", "id", name="uq_provider_business"),
    )
    op.create_index(
        "ix_providers_business_active_sort", "providers", ["business_id", "is_active", "sort_order"], unique=False
    )  # noqa: E501
    op.create_table(
        "services",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("business_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("duration_minutes", sa.Integer(), nullable=False),
        sa.Column("price_amount", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("duration_minutes >= 5 AND duration_minutes <= 720", name="check_duration"),
        sa.CheckConstraint("price_amount >= 0", name="check_price"),
        sa.ForeignKeyConstraint(["business_id"], ["businesses.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("business_id", "id", name="uq_service_business"),
    )
    op.create_index(
        "ix_services_business_active_sort", "services", ["business_id", "is_active", "sort_order"], unique=False
    )  # noqa: E501
    op.create_table(
        "provider_services",
        sa.Column("business_id", sa.UUID(), nullable=False),
        sa.Column("provider_id", sa.UUID(), nullable=False),
        sa.Column("service_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["business_id", "provider_id"], ["providers.business_id", "providers.id"], ondelete="CASCADE"
        ),  # noqa: E501
        sa.ForeignKeyConstraint(
            ["business_id", "service_id"], ["services.business_id", "services.id"], ondelete="CASCADE"
        ),  # noqa: E501
        sa.PrimaryKeyConstraint("provider_id", "service_id", name="pk_provider_services"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("provider_services")
    op.drop_index("ix_services_business_active_sort", table_name="services")
    op.drop_table("services")
    op.drop_index("ix_providers_business_active_sort", table_name="providers")
    op.drop_table("providers")
    # ### end Alembic commands ###
