"""create_rules_and_time_off

Revision ID: c2f6f70806e9
Revises: b24f49968702
Create Date: 2026-08-08 22:43:33.704524

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c2f6f70806e9"
down_revision: Union[str, Sequence[str], None] = "b24f49968702"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "availability_rules",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("business_id", sa.UUID(), nullable=False),
        sa.Column("provider_id", sa.UUID(), nullable=False),
        sa.Column("weekday", sa.SmallInteger(), nullable=False),
        sa.Column("start_time", sa.Time(), nullable=False),
        sa.Column("end_time", sa.Time(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("end_time > start_time", name="check_time_order"),
        sa.CheckConstraint("weekday >= 0 AND weekday <= 6", name="check_weekday"),
        sa.ForeignKeyConstraint(
            ["business_id", "provider_id"], ["providers.business_id", "providers.id"], ondelete="CASCADE"
        ),  # noqa: E501
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_avail_rules_b_p_w_s",
        "availability_rules",
        ["business_id", "provider_id", "weekday", "start_time"],
        unique=False,
    )  # noqa: E501
    op.create_table(
        "time_off",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("business_id", sa.UUID(), nullable=False),
        sa.Column("provider_id", sa.UUID(), nullable=False),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("reason", sa.String(length=240), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("ends_at > starts_at", name="check_time_off_order"),
        sa.ForeignKeyConstraint(
            ["business_id", "provider_id"], ["providers.business_id", "providers.id"], ondelete="CASCADE"
        ),  # noqa: E501
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_time_off_b_p_s", "time_off", ["business_id", "provider_id", "starts_at"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_time_off_b_p_s", table_name="time_off")
    op.drop_table("time_off")
    op.drop_index("ix_avail_rules_b_p_w_s", table_name="availability_rules")
    op.drop_table("availability_rules")
    # ### end Alembic commands ###
