"""create_businesses_and_enums

Revision ID: caa00e08ebad
Revises:
Create Date: 2026-08-08 22:39:32.300969

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "caa00e08ebad"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS btree_gist;")

    booking_status = postgresql.ENUM(
        "confirmed", "completed", "cancelled", "no_show", name="booking_status", create_type=False
    )  # noqa: E501
    booking_status.create(op.get_bind(), checkfirst=True)

    booking_source = postgresql.ENUM("public", "admin", name="booking_source", create_type=False)
    booking_source.create(op.get_bind(), checkfirst=True)

    email_delivery_status = postgresql.ENUM(
        "not_requested", "pending", "sent", "failed", name="email_delivery_status", create_type=False
    )  # noqa: E501
    email_delivery_status.create(op.get_bind(), checkfirst=True)
    op.create_table(
        "businesses",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("slug", sa.String(length=80), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("locale", sa.String(length=16), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("email", sa.String(length=254), nullable=False),
        sa.Column("phone", sa.String(length=32), nullable=True),
        sa.Column("address", sa.String(length=300), nullable=True),
        sa.Column("minimum_booking_notice_minutes", sa.Integer(), nullable=False),
        sa.Column("booking_horizon_days", sa.Integer(), nullable=False),
        sa.Column("slot_interval_minutes", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("booking_horizon_days >= 1 AND booking_horizon_days <= 365", name="check_horizon"),
        sa.CheckConstraint("minimum_booking_notice_minutes >= 0", name="check_min_notice"),
        sa.CheckConstraint("slot_interval_minutes >= 1 AND slot_interval_minutes <= 120", name="check_slot_interval"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("businesses")
    op.execute("DROP TYPE IF EXISTS email_delivery_status;")
    op.execute("DROP TYPE IF EXISTS booking_source;")
    op.execute("DROP TYPE IF EXISTS booking_status;")
    op.execute("DROP EXTENSION IF EXISTS btree_gist;")
    # ### end Alembic commands ###
